[package]
name = "custom_account"
authors = [""]
compiler_version = ">=0.25.0"
type = "contract"

[features]
enums = true

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v2.0.2", directory = "noir-projects/aztec-nr/aztec" }
compressed_string = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v2.0.2", directory = "noir-projects/aztec-nr/compressed-string" }
schnorr = { tag = "v0.1.3", git = "https://github.com/noir-lang/schnorr" }
value_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v2.0.2", directory="noir-projects/aztec-nr/value-note" }
address_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v2.0.2", directory="noir-projects/aztec-nr/address-note" }
protocol_types = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v2.0.2", directory="noir-projects/noir-protocol-circuits/crates/types"}