[package]
name = "custom_account"
authors = [""]
compiler_version = ">=0.18.0"
type = "contract"

[features]
enums = true

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v2.0.2", directory = "noir-projects/aztec-nr/aztec" }
schnorr = { git = "https://github.com/noir-lang/schnorr", tag = "v0.1.3" }
