[package]
name = "easy_private_voting_contract"
type = "contract"
authors = [""]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v1.2.1", directory = "noir-projects/aztec-nr/aztec" }
schnorr = { tag = "v0.1.3", git = "https://github.com/noir-lang/schnorr" }
token = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v1.2.1", directory = "noir-projects/noir-contracts/contracts/app/token_contract" }
wormhole = { git = "https://github.com/NethermindEth/wormhole", tag = "aztec", directory = "aztec/contracts" }