[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "wormhole/=lib/wormhole-solidity-sdk/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"