
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import MultisigAccountContractArtifactJson from '../../target/cross_chain-MultisigAccount.json' with { type: 'json' };
export const MultisigAccountContractArtifact = loadContractArtifact(MultisigAccountContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract MultisigAccount;
 */
export class MultisigAccountContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, MultisigAccountContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, MultisigAccountContract.artifact, wallet) as Promise<MultisigAccountContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, signers: AztecAddressLike[], initial_threshold: (bigint | number), signers_pk_x: FieldLike[], signers_pk_y: FieldLike[]) {
    return new DeployMethod<MultisigAccountContract>(PublicKeys.default(), wallet, MultisigAccountContractArtifact, MultisigAccountContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, signers: AztecAddressLike[], initial_threshold: (bigint | number), signers_pk_x: FieldLike[], signers_pk_y: FieldLike[]) {
    return new DeployMethod<MultisigAccountContract>(publicKeys, wallet, MultisigAccountContractArtifact, MultisigAccountContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MultisigAccountContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<MultisigAccountContract['methods'][M]>
  ) {
    return new DeployMethod<MultisigAccountContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      MultisigAccountContractArtifact,
      MultisigAccountContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MultisigAccountContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(MultisigAccountContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'master_signer' | 'threshold' | 'signer_count' | 'is_signer' | 'signer_pubkeys_x' | 'signer_pubkeys_y' | 'executed_message_hashes'> {
      return {
        master_signer: {
      slot: new Fr(1n),
    },
threshold: {
      slot: new Fr(2n),
    },
signer_count: {
      slot: new Fr(3n),
    },
is_signer: {
      slot: new Fr(4n),
    },
signer_pubkeys_x: {
      slot: new Fr(5n),
    },
signer_pubkeys_y: {
      slot: new Fr(6n),
    },
executed_message_hashes: {
      slot: new Fr(7n),
    }
      } as ContractStorageLayout<'master_signer' | 'threshold' | 'signer_count' | 'is_signer' | 'signer_pubkeys_x' | 'signer_pubkeys_y' | 'executed_message_hashes'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** add_signer(message_hash: field, new_signer: struct, new_signer_pk_x: field, new_signer_pk_y: field, signatures: array) */
    add_signer: ((message_hash: FieldLike, new_signer: AztecAddressLike, new_signer_pk_x: FieldLike, new_signer_pk_y: FieldLike, signatures: { signature: (bigint | number)[], owner: AztecAddressLike }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** change_threshold(message_hash: field, new_threshold: integer, signatures: array) */
    change_threshold: ((message_hash: FieldLike, new_threshold: (bigint | number), signatures: { signature: (bigint | number)[], owner: AztecAddressLike }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(signers: array, initial_threshold: integer, signers_pk_x: array, signers_pk_y: array) */
    constructor: ((signers: AztecAddressLike[], initial_threshold: (bigint | number), signers_pk_x: FieldLike[], signers_pk_y: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** execute_cross_chain_intent(message_hash: field, target_chain: field, target_contract: struct, intent_type: field, amount: field, recipient: struct, wormhole_address: struct, signatures: array) */
    execute_cross_chain_intent: ((message_hash: FieldLike, target_chain: FieldLike, target_contract: AztecAddressLike, intent_type: FieldLike, amount: FieldLike, recipient: AztecAddressLike, wormhole_address: AztecAddressLike, signatures: { signature: (bigint | number)[], owner: AztecAddressLike }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_threshold() */
    get_threshold: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_address_signer(signer: struct) */
    is_address_signer: ((signer: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_message_initialized(message_hash: field) */
    is_message_initialized: ((message_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_signer_initialized(signer: struct) */
    is_signer_initialized: ((signer: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** remove_signer(message_hash: field, target_signer: struct, signatures: array) */
    remove_signer: ((message_hash: FieldLike, target_signer: AztecAddressLike, signatures: { signature: (bigint | number)[], owner: AztecAddressLike }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
